#!/bin/bash


if [ "$#" -ne 1 ]; then
    echo 8map | figlet
    echo "          adot8 <3"
    echo
    echo "Usage: 8map <IP_address>"
    exit 1
fi

echo 8map | figlet 
echo "          adot8 <3"

ip_address=$1

echo
echo "[+] Scanning $ip_address [65535 TCP ports]"
echo
# Run initial nmap scan to get open ports
open_ports=$(nmap -p- --min-rate=1000 -Pn $ip_address | grep ^[0-9] | cut -d '/' -f 1 | tr '\n' ',' | sed 's/,$//')

# Run detailed scan with detected open ports
echo
echo "[+] Enumerating $ip_address [$open_ports]"
echo
sleep 1
nmap -p $open_ports -sC -sV -T5 -Pn $ip_address
echo
echo "[+] Enumerating $ip_address for vulnerabilities [$open_ports]"
echo
sleep 1
nmap -p $open_ports --script vuln -T5 -Pn $ip_address
echo
echo "[+] Scanning $ip_address [1000 UDP ports]"
nmap -sU -T4 -F -v $ip_address
echo
echo "[+] Completed!"
